// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package mock

import (
	"sync"
)

var (
	lockLoaderMockLoad sync.RWMutex
)

// LoaderMock is a mock implementation of Loader.
//
//     func TestSomethingThatUsesLoader(t *testing.T) {
//
//         // make and configure a mocked Loader
//         mockedLoader := &LoaderMock{
//             LoadFunc: func(dest interface{}) error {
// 	               panic("TODO: mock out the Load method")
//             },
//         }
//
//         // TODO: use mockedLoader in code that requires Loader
//         //       and then make assertions.
//
//     }
type LoaderMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func(dest interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
			// Dest is the dest argument value.
			Dest interface{}
		}
	}
}

// Load calls LoadFunc.
func (mock *LoaderMock) Load(dest interface{}) error {
	if mock.LoadFunc == nil {
		panic("moq: LoaderMock.LoadFunc is nil but Loader.Load was just called")
	}
	callInfo := struct {
		Dest interface{}
	}{
		Dest: dest,
	}
	lockLoaderMockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	lockLoaderMockLoad.Unlock()
	return mock.LoadFunc(dest)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//     len(mockedLoader.LoadCalls())
func (mock *LoaderMock) LoadCalls() []struct {
	Dest interface{}
} {
	var calls []struct {
		Dest interface{}
	}
	lockLoaderMockLoad.RLock()
	calls = mock.calls.Load
	lockLoaderMockLoad.RUnlock()
	return calls
}
